apiVersion: apps/v1
kind: Deployment

metadata:
  name: mecaniqa-java
  namespace: mecaniqa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mecaniqa-java

  template:
    metadata:
      labels:
        app: mecaniqa-java

    spec:
      containers:
        - name: mecaniqa-java
          image: mecaniqa-boa-vista-java:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mecaniqa-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mecaniqa-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mecaniqa-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mecaniqa-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mecaniqa-secret
                  key: MYSQL_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: mecaniqa-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: mecaniqa-config
                  key: REDIS_PORT
