apiVersion: apps/v1
kind: Deployment

metadata:
  name: mecaniqa-redis
  namespace: mecaniqa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mecaniqa-redis

  template:
    metadata:
      labels:
        app: mecaniqa-redis

    spec:
      containers:
        - name: mecaniqa-redis
          image: mecaniqa-boa-vista-redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
