# valores em base64, so para fins didaticos
apiVersion: v1
kind: Secret

metadata:
  name: mecaniqa-secret
  namespace: mecaniqa

type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
  MYSQL_USER: bWVjYW5pcWE=
  MYSQL_PASSWORD: bWVjYW5pcWExMjM=
